source 'https://rubygems.org'

gem 'coffee-rails'
gem 'ember-rails'
gem 'ember-source'
gem 'emblem-rails'
gem 'jbuilder'
gem 'jquery-rails'
gem 'pg'
gem 'rails', '4.0.4'
gem 'sass-rails'
gem 'uglifier'
gem 'active_model_serializers'
gem 'ffaker'
gem 'puma'
gem 'rails_12factor'